// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
)

const countAPIKeysByUserID = `-- name: CountAPIKeysByUserID :one
SELECT COUNT(*)
FROM api_keys
WHERE user_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountAPIKeysByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeysByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, name, key_hash, key_prefix, scopes, last_used_at, created, updated, deleted_at
FROM api_keys
WHERE key_hash = ? AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.Created,
		&i.Updated,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, name, key_hash, key_prefix, scopes, last_used_at, created, updated, deleted_at
FROM api_keys
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id int64) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.Created,
		&i.Updated,
		&i.DeletedAt,
	)
	return i, err
}

const getAPIKeysByPrefix = `-- name: GetAPIKeysByPrefix :many
SELECT id, user_id, name, key_hash, key_prefix, scopes, last_used_at, created, updated, deleted_at
FROM api_keys
WHERE key_prefix = ? AND deleted_at IS NULL
`

func (q *Queries) GetAPIKeysByPrefix(ctx context.Context, keyPrefix string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByPrefix, keyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.Created,
			&i.Updated,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAPIKeysByUserID = `-- name: GetAPIKeysByUserID :many
SELECT id, user_id, name, key_hash, key_prefix, scopes, last_used_at, created, updated, deleted_at
FROM api_keys
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created DESC
`

func (q *Queries) GetAPIKeysByUserID(ctx context.Context, userID int64) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.Created,
			&i.Updated,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAPIKey = `-- name: InsertAPIKey :execlastid
INSERT INTO api_keys (user_id, name, key_hash, key_prefix, scopes)
VALUES (?, ?, ?, ?, ?)
`

type InsertAPIKeyParams struct {
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
	KeyHash   string `json:"key_hash"`
	KeyPrefix string `json:"key_prefix"`
	Scopes    string `json:"scopes"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAPIKey,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const softDeleteAPIKey = `-- name: SoftDeleteAPIKey :exec
UPDATE api_keys
SET deleted_at = CURRENT_TIMESTAMP, updated = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteAPIKey, id)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys
SET name = ?, scopes = ?, updated = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateAPIKeyParams struct {
	Name   string `json:"name"`
	Scopes string `json:"scopes"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey, arg.Name, arg.Scopes, arg.ID)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = CURRENT_TIMESTAMP, updated = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
