// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Client struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt interface{} `json:"deleted_at"`
}

type Project struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	ClientID  int64       `json:"client_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt interface{} `json:"deleted_at"`
}

type Timesheet struct {
	ID          int64          `json:"id"`
	ProjectID   int64          `json:"project_id"`
	WorkDate    time.Time      `json:"work_date"`
	HoursWorked float64        `json:"hours_worked"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedAt   interface{}    `json:"deleted_at"`
	Description sql.NullString `json:"description"`
}
