// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetAllClients(ctx context.Context) ([]GetAllClientsRow, error)
	GetClient(ctx context.Context, id int64) (GetClientRow, error)
	InsertClient(ctx context.Context, name string) (int64, error)
}

var _ Querier = (*Queries)(nil)
