// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteClient(ctx context.Context, id int64) error
	DeleteInvoice(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	DeleteTimesheet(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllClients(ctx context.Context) ([]GetAllClientsRow, error)
	GetAllProjectsWithClient(ctx context.Context) ([]GetAllProjectsWithClientRow, error)
	GetAllSettings(ctx context.Context) ([]Setting, error)
	GetClient(ctx context.Context, id int64) (GetClientRow, error)
	GetClientsCount(ctx context.Context) (int64, error)
	GetClientsWithPagination(ctx context.Context, arg GetClientsWithPaginationParams) ([]GetClientsWithPaginationRow, error)
	GetInvoice(ctx context.Context, id int64) (GetInvoiceRow, error)
	GetInvoiceComprehensiveForPDF(ctx context.Context, id int64) (GetInvoiceComprehensiveForPDFRow, error)
	GetInvoiceForPDF(ctx context.Context, id int64) (GetInvoiceForPDFRow, error)
	GetInvoicesByProject(ctx context.Context, projectID int64) ([]GetInvoicesByProjectRow, error)
	GetPaidInvoicesForYear(ctx context.Context, arg GetPaidInvoicesForYearParams) ([]GetPaidInvoicesForYearRow, error)
	GetProject(ctx context.Context, id int64) (GetProjectRow, error)
	GetProjectsByClient(ctx context.Context, clientID int64) ([]GetProjectsByClientRow, error)
	GetProjectsCount(ctx context.Context) (int64, error)
	GetProjectsWithClientPagination(ctx context.Context, arg GetProjectsWithClientPaginationParams) ([]GetProjectsWithClientPaginationRow, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetTimesheet(ctx context.Context, id int64) (GetTimesheetRow, error)
	GetTimesheetsByProject(ctx context.Context, projectID int64) ([]GetTimesheetsByProjectRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	InsertClient(ctx context.Context, arg InsertClientParams) (int64, error)
	InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (int64, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (int64, error)
	InsertTimesheet(ctx context.Context, arg InsertTimesheetParams) (int64, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (int64, error)
	SearchClientsCount(ctx context.Context, arg SearchClientsCountParams) (int64, error)
	SearchClientsWithPagination(ctx context.Context, arg SearchClientsWithPaginationParams) ([]SearchClientsWithPaginationRow, error)
	SearchProjectsCount(ctx context.Context, arg SearchProjectsCountParams) (int64, error)
	SearchProjectsWithClientPagination(ctx context.Context, arg SearchProjectsWithClientPaginationParams) ([]SearchProjectsWithClientPaginationRow, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) error
	UpdateTimesheet(ctx context.Context, arg UpdateTimesheetParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UserExists(ctx context.Context, email string) (int64, error)
}

var _ Querier = (*Queries)(nil)
