// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const deleteUser = `-- name: DeleteUser :exec
UPDATE user 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, hashed_password, require_password_change, created_at, updated_at, deleted_at
FROM user
WHERE deleted_at IS NULL
ORDER BY name
`

type GetAllUsersRow struct {
	ID                    int64       `json:"id"`
	Name                  string      `json:"name"`
	Email                 string      `json:"email"`
	HashedPassword        interface{} `json:"hashed_password"`
	RequirePasswordChange int64       `json:"require_password_change"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
	DeletedAt             interface{} `json:"deleted_at"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.HashedPassword,
			&i.RequirePasswordChange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, hashed_password, require_password_change, created_at, updated_at, deleted_at
FROM user
WHERE email = ? AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID                    int64       `json:"id"`
	Name                  string      `json:"name"`
	Email                 string      `json:"email"`
	HashedPassword        interface{} `json:"hashed_password"`
	RequirePasswordChange int64       `json:"require_password_change"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
	DeletedAt             interface{} `json:"deleted_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.RequirePasswordChange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, hashed_password, require_password_change, created_at, updated_at, deleted_at
FROM user
WHERE id = ? AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID                    int64       `json:"id"`
	Name                  string      `json:"name"`
	Email                 string      `json:"email"`
	HashedPassword        interface{} `json:"hashed_password"`
	RequirePasswordChange int64       `json:"require_password_change"`
	CreatedAt             time.Time   `json:"created_at"`
	UpdatedAt             time.Time   `json:"updated_at"`
	DeletedAt             interface{} `json:"deleted_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.HashedPassword,
		&i.RequirePasswordChange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :execlastid
INSERT INTO user (name, email, hashed_password, require_password_change)
VALUES (?, ?, ?, ?)
`

type InsertUserParams struct {
	Name                  string      `json:"name"`
	Email                 string      `json:"email"`
	HashedPassword        interface{} `json:"hashed_password"`
	RequirePasswordChange int64       `json:"require_password_change"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.HashedPassword,
		arg.RequirePasswordChange,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user
SET name = ?, email = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE user
SET hashed_password = ?, require_password_change = 0, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	HashedPassword interface{} `json:"hashed_password"`
	ID             int64       `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.HashedPassword, arg.ID)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM user WHERE email = ? AND deleted_at IS NULL)
`

func (q *Queries) UserExists(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userExists, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
